import type { ClassOffering } from '@/types/class';

export const MOCK_CLASSES: ClassOffering[] = [
  {
    id: 'class-1',
    studioId: 'studio-1',
    title: 'Vinyasa Flow',
    description: 'A dynamic yoga practice linking breath with movement. Build strength, flexibility, and mindfulness through flowing sequences.',
    category: 'yoga',
    difficulty: 'intermediate',
    duration: 60,
    price: 3500,
    instructorId: 'inst-1',
    defaultCapacity: 20,
    tags: ['vinyasa', 'flow', 'flexibility'],
    images: ['/images/classes/vinyasa-1.jpg'],
    rules: ['Bring your own mat or rent one', 'Arrive 10 min early', 'No shoes in studio'],
    cancellationWindow: 24,
  },
  {
    id: 'class-2',
    studioId: 'studio-1',
    title: 'Morning Meditation',
    description: 'Start your day with guided meditation and breathing exercises. Perfect for beginners and experienced practitioners.',
    category: 'meditation',
    difficulty: 'all_levels',
    duration: 30,
    instructorId: 'inst-7',
    defaultCapacity: 15,
    tags: ['meditation', 'mindfulness', 'breathing'],
    images: ['/images/classes/meditation-1.jpg'],
    rules: ['Wear comfortable clothing', 'Arrive 5 min early'],
    cancellationWindow: 12,
  },
  {
    id: 'class-3',
    studioId: 'studio-2',
    title: 'Boxing Fundamentals',
    description: 'Learn proper boxing technique including stance, jabs, crosses, and hooks. Great cardio workout with self-defense skills.',
    category: 'boxing',
    difficulty: 'beginner',
    duration: 45,
    price: 4000,
    instructorId: 'inst-2',
    defaultCapacity: 16,
    tags: ['boxing', 'cardio', 'technique'],
    images: ['/images/classes/boxing-1.jpg'],
    rules: ['Wraps provided for first-timers', 'Bring water bottle', 'Gloves available'],
    cancellationWindow: 24,
  },
  {
    id: 'class-4',
    studioId: 'studio-2',
    title: 'HIIT Blast',
    description: 'High-intensity interval training combining boxing moves with bodyweight exercises. Maximum calorie burn in 45 minutes.',
    category: 'hiit',
    difficulty: 'advanced',
    duration: 45,
    price: 4000,
    instructorId: 'inst-8',
    defaultCapacity: 20,
    tags: ['hiit', 'intense', 'cardio', 'strength'],
    images: ['/images/classes/hiit-1.jpg'],
    rules: ['Bring towel and water', 'Not recommended for beginners'],
    cancellationWindow: 24,
  },
  {
    id: 'class-5',
    studioId: 'studio-3',
    title: 'Reformer Pilates',
    description: 'Pilates on the reformer machine targeting core strength, posture, and muscle toning with precise, controlled movements.',
    category: 'pilates',
    difficulty: 'intermediate',
    duration: 50,
    price: 5000,
    instructorId: 'inst-3',
    defaultCapacity: 10,
    tags: ['reformer', 'core', 'toning'],
    images: ['/images/classes/reformer-1.jpg'],
    rules: ['Grip socks required', 'Max 10 people', 'No late entry'],
    cancellationWindow: 48,
  },
  {
    id: 'class-6',
    studioId: 'studio-3',
    title: 'Mat Pilates',
    description: 'Classical mat Pilates focusing on core engagement, flexibility, and body awareness. Suitable for all fitness levels.',
    category: 'pilates',
    difficulty: 'all_levels',
    duration: 55,
    price: 3000,
    instructorId: 'inst-3',
    defaultCapacity: 18,
    tags: ['mat', 'core', 'flexibility'],
    images: ['/images/classes/mat-pilates-1.jpg'],
    rules: ['Mats provided', 'Wear form-fitting clothes'],
    cancellationWindow: 24,
  },
  {
    id: 'class-7',
    studioId: 'studio-4',
    title: 'Rhythm Ride',
    description: 'A music-driven indoor cycling experience. Pedal to the beat with motivating playlists and immersive lighting.',
    category: 'cycling',
    difficulty: 'intermediate',
    duration: 45,
    price: 4500,
    instructorId: 'inst-6',
    defaultCapacity: 30,
    tags: ['cycling', 'rhythm', 'cardio'],
    images: ['/images/classes/rhythm-ride-1.jpg'],
    rules: ['Cycling shoes available', 'Arrive 5 min early to set up bike', 'Towel provided'],
    cancellationWindow: 12,
  },
  {
    id: 'class-8',
    studioId: 'studio-4',
    title: 'Power Ride',
    description: 'Performance-focused cycling class with intervals, climbs, and sprints. Track your metrics and push your limits.',
    category: 'cycling',
    difficulty: 'advanced',
    duration: 50,
    price: 4500,
    instructorId: 'inst-6',
    defaultCapacity: 30,
    tags: ['cycling', 'power', 'performance'],
    images: ['/images/classes/power-ride-1.jpg'],
    rules: ['Heart rate monitor recommended', 'Clip-in shoes available'],
    cancellationWindow: 12,
  },
  {
    id: 'class-9',
    studioId: 'studio-5',
    title: 'Salsa Social',
    description: 'Fun and energetic salsa class. Learn basic steps, partner work, and styling. No partner needed!',
    category: 'dance',
    difficulty: 'beginner',
    duration: 60,
    price: 3000,
    instructorId: 'inst-5',
    defaultCapacity: 24,
    tags: ['salsa', 'latin', 'partner', 'social'],
    images: ['/images/classes/salsa-1.jpg'],
    rules: ['No special shoes required', 'Singles welcome', 'Rotation format'],
    cancellationWindow: 24,
  },
  {
    id: 'class-10',
    studioId: 'studio-5',
    title: 'Contemporary Dance',
    description: 'Explore contemporary dance techniques including floor work, improvisation, and choreography.',
    category: 'dance',
    difficulty: 'intermediate',
    duration: 75,
    price: 3500,
    instructorId: 'inst-5',
    defaultCapacity: 16,
    tags: ['contemporary', 'technique', 'expression'],
    images: ['/images/classes/contemporary-1.jpg'],
    rules: ['Barefoot or dance socks', 'Comfortable clothes'],
    cancellationWindow: 24,
  },
  {
    id: 'class-11',
    studioId: 'studio-6',
    title: 'CrossFit WOD',
    description: 'Daily workout combining Olympic lifting, gymnastics, and metabolic conditioning. Scaled options for all levels.',
    category: 'crossfit',
    difficulty: 'all_levels',
    duration: 60,
    price: 4500,
    instructorId: 'inst-4',
    defaultCapacity: 20,
    tags: ['crossfit', 'wod', 'strength', 'conditioning'],
    images: ['/images/classes/crossfit-1.jpg'],
    rules: ['Long socks for rope climbs', 'Own shoes required', 'Water bottle mandatory'],
    cancellationWindow: 24,
  },
  {
    id: 'class-12',
    studioId: 'studio-6',
    title: 'Olympic Lifting',
    description: 'Dedicated class for snatch and clean & jerk technique. Small groups for individual coaching.',
    category: 'crossfit',
    difficulty: 'intermediate',
    duration: 75,
    price: 5000,
    instructorId: 'inst-4',
    defaultCapacity: 8,
    tags: ['olympic', 'lifting', 'technique', 'strength'],
    images: ['/images/classes/oly-lifting-1.jpg'],
    rules: ['Weightlifting shoes required', 'Wrist wraps recommended'],
    cancellationWindow: 48,
  },
  {
    id: 'class-13',
    studioId: 'studio-7',
    title: 'Gentle Hatha Yoga',
    description: 'Slow-paced yoga with long holds. Focus on alignment, breath, and deep relaxation. Great for stress relief.',
    category: 'yoga',
    difficulty: 'beginner',
    duration: 75,
    price: 3000,
    instructorId: 'inst-9',
    defaultCapacity: 18,
    tags: ['hatha', 'gentle', 'relaxation'],
    images: ['/images/classes/hatha-1.jpg'],
    rules: ['Props provided', 'Blankets available'],
    cancellationWindow: 24,
  },
  {
    id: 'class-14',
    studioId: 'studio-7',
    title: 'Deep Stretch & Recovery',
    description: 'Restorative stretching session targeting major muscle groups. Perfect after intense training days.',
    category: 'stretching',
    difficulty: 'all_levels',
    duration: 45,
    price: 2500,
    instructorId: 'inst-9',
    defaultCapacity: 20,
    tags: ['stretching', 'recovery', 'flexibility'],
    images: ['/images/classes/stretch-1.jpg'],
    rules: ['Wear comfortable clothes', 'Foam rollers provided'],
    cancellationWindow: 12,
  },
  {
    id: 'class-15',
    studioId: 'studio-8',
    title: 'Functional Strength',
    description: 'Full-body functional training using kettlebells, TRX, and bodyweight. Build practical, everyday strength.',
    category: 'functional',
    difficulty: 'intermediate',
    duration: 50,
    price: 3500,
    instructorId: 'inst-10',
    defaultCapacity: 16,
    tags: ['functional', 'strength', 'kettlebell'],
    images: ['/images/classes/functional-1.jpg'],
    rules: ['Athletic shoes required', 'Bring water and towel'],
    cancellationWindow: 24,
  },
  {
    id: 'class-16',
    studioId: 'studio-8',
    title: 'Tabata Fire',
    description: '20 seconds on, 10 seconds off. Pure Tabata intervals for maximum metabolic boost in minimum time.',
    category: 'hiit',
    difficulty: 'advanced',
    duration: 30,
    price: 3000,
    instructorId: 'inst-10',
    defaultCapacity: 24,
    tags: ['tabata', 'hiit', 'intense', 'short'],
    images: ['/images/classes/tabata-1.jpg'],
    rules: ['Heart rate monitor recommended', 'Bring towel'],
    cancellationWindow: 12,
  },
  {
    id: 'class-17',
    studioId: 'studio-9',
    title: 'Sunrise Vinyasa',
    description: 'Early morning Vinyasa flow to energize your day. Gentle warm-up building to dynamic sequences.',
    category: 'yoga',
    difficulty: 'all_levels',
    duration: 60,
    price: 3500,
    instructorId: 'inst-1',
    defaultCapacity: 12,
    tags: ['vinyasa', 'morning', 'energy'],
    images: ['/images/classes/sunrise-vinyasa-1.jpg'],
    rules: ['Mats and props provided', 'Arrive 5 min early'],
    cancellationWindow: 24,
  },
  {
    id: 'class-18',
    studioId: 'studio-9',
    title: 'Yin Yoga',
    description: 'Slow-paced style holding poses for 3-5 minutes. Targets connective tissues and promotes deep flexibility.',
    category: 'yoga',
    difficulty: 'beginner',
    duration: 75,
    price: 3500,
    instructorId: 'inst-7',
    defaultCapacity: 12,
    tags: ['yin', 'deep-stretch', 'meditative'],
    images: ['/images/classes/yin-yoga-1.jpg'],
    rules: ['Bolsters and blocks provided', 'Warm clothes recommended'],
    cancellationWindow: 24,
  },
  {
    id: 'class-19',
    studioId: 'studio-2',
    title: 'Kickboxing Cardio',
    description: 'High-energy kickboxing-inspired workout. Punch, kick, and sweat your way to fitness. No contact.',
    category: 'boxing',
    difficulty: 'all_levels',
    duration: 50,
    price: 4000,
    instructorId: 'inst-2',
    defaultCapacity: 20,
    tags: ['kickboxing', 'cardio', 'no-contact'],
    images: ['/images/classes/kickboxing-1.jpg'],
    rules: ['Gloves provided', 'Water bottle required'],
    cancellationWindow: 24,
  },
  {
    id: 'class-20',
    studioId: 'studio-8',
    title: 'Morning HIIT',
    description: 'Start your day strong with a 45-minute HIIT circuit. Modifications available for all levels.',
    category: 'hiit',
    difficulty: 'intermediate',
    duration: 45,
    price: 3500,
    instructorId: 'inst-8',
    defaultCapacity: 20,
    tags: ['hiit', 'morning', 'circuit'],
    images: ['/images/classes/morning-hiit-1.jpg'],
    rules: ['Indoor shoes required', 'Towel recommended'],
    cancellationWindow: 24,
  },
];
