import type { Instructor } from '@/types/instructor';

export const MOCK_INSTRUCTORS: Instructor[] = [
  {
    id: 'inst-1',
    name: 'Valentina Rossi',
    bio: 'Certified yoga instructor with 10+ years of experience. Specializes in Vinyasa and Ashtanga styles.',
    certifications: ['RYT-500', 'Yoga Alliance'],
    profileImage: '/images/instructors/valentina.jpg',
    specialties: ['yoga', 'meditation'],
  },
  {
    id: 'inst-2',
    name: 'Martín López',
    bio: 'Former competitive boxer turned fitness instructor. Passionate about making boxing accessible to everyone.',
    certifications: ['ACE Personal Trainer', 'Boxing Fitness Certified'],
    profileImage: '/images/instructors/martin.jpg',
    specialties: ['boxing', 'hiit'],
  },
  {
    id: 'inst-3',
    name: 'Camila Fernández',
    bio: 'Pilates and barre specialist. Trained in classical and contemporary Pilates methods.',
    certifications: ['BASI Pilates', 'Balanced Body'],
    profileImage: '/images/instructors/camila.jpg',
    specialties: ['pilates', 'stretching'],
  },
  {
    id: 'inst-4',
    name: 'Lucas García',
    bio: 'CrossFit Level 2 trainer and functional fitness enthusiast. Believes in building strength for life.',
    certifications: ['CrossFit L2', 'NSCA-CSCS'],
    profileImage: '/images/instructors/lucas.jpg',
    specialties: ['crossfit', 'functional'],
  },
  {
    id: 'inst-5',
    name: 'Sofía Martínez',
    bio: 'Professional dancer and choreographer. Teaches various dance styles from salsa to contemporary.',
    certifications: ['Dance Education Certified', 'Zumba Instructor'],
    profileImage: '/images/instructors/sofia.jpg',
    specialties: ['dance'],
  },
  {
    id: 'inst-6',
    name: 'Diego Alvarez',
    bio: 'Spinning and cycling coach with a background in competitive cycling. High-energy, results-driven sessions.',
    certifications: ['Spinning Certified', 'ACE Group Fitness'],
    profileImage: '/images/instructors/diego.jpg',
    specialties: ['cycling', 'hiit'],
  },
  {
    id: 'inst-7',
    name: 'Ana Ruiz',
    bio: 'Mindfulness and meditation teacher with a holistic approach to wellness. 8 years of practice.',
    certifications: ['MBSR Certified', 'Yoga Nidra'],
    profileImage: '/images/instructors/ana.jpg',
    specialties: ['meditation', 'yoga'],
  },
  {
    id: 'inst-8',
    name: 'Nicolás Torres',
    bio: 'HIIT and functional training specialist. Creates challenging, adaptable workouts for all fitness levels.',
    certifications: ['NASM-CPT', 'TRX Certified'],
    profileImage: '/images/instructors/nicolas.jpg',
    specialties: ['hiit', 'functional'],
  },
  {
    id: 'inst-9',
    name: 'Isabella Moreno',
    bio: 'Yoga and stretching expert focused on flexibility, recovery, and injury prevention.',
    certifications: ['RYT-200', 'Fascial Stretch Therapy'],
    profileImage: '/images/instructors/isabella.jpg',
    specialties: ['yoga', 'stretching'],
  },
  {
    id: 'inst-10',
    name: 'Tomás Herrera',
    bio: 'Certified personal trainer specializing in HIIT and strength. Formerly trained professional athletes.',
    certifications: ['ISSA-CPT', 'Kettlebell Certified'],
    profileImage: '/images/instructors/tomas.jpg',
    specialties: ['hiit', 'crossfit', 'functional'],
  },
];
