import type { Studio } from '@/types/studio';

export const MOCK_STUDIOS: Studio[] = [
  {
    id: 'studio-1',
    name: 'Zen Flow Studio',
    address: 'Honduras 4700, Palermo',
    neighborhood: 'palermo',
    geoCoordinates: { lat: -34.5875, lng: -58.4295 },
    description: 'A tranquil yoga and meditation studio in the heart of Palermo, offering classes for all levels in a beautifully restored townhouse.',
    images: ['/images/studios/zen-flow-1.jpg', '/images/studios/zen-flow-2.jpg'],
    facilities: ['Changing rooms', 'Showers', 'Mat rental', 'Water fountain', 'Lockers'],
    operatingHours: [
      { day: 'Monday', open: '07:00', close: '21:00' },
      { day: 'Tuesday', open: '07:00', close: '21:00' },
      { day: 'Wednesday', open: '07:00', close: '21:00' },
      { day: 'Thursday', open: '07:00', close: '21:00' },
      { day: 'Friday', open: '07:00', close: '20:00' },
      { day: 'Saturday', open: '09:00', close: '14:00' },
      { day: 'Sunday', open: '10:00', close: '13:00' },
    ],
    contactInfo: { phone: '+54 11 4832-1234', email: 'info@zenflow.com.ar', website: 'https://zenflow.com.ar' },
    managerUserId: 'user-studio-1',
    status: 'approved',
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: 'studio-2',
    name: 'FitBox Arena',
    address: 'Av. Santa Fe 2450, Recoleta',
    neighborhood: 'recoleta',
    geoCoordinates: { lat: -34.5955, lng: -58.3985 },
    description: 'High-energy boxing and HIIT studio with state-of-the-art equipment. Get fit, get strong, have fun.',
    images: ['/images/studios/fitbox-1.jpg', '/images/studios/fitbox-2.jpg'],
    facilities: ['Boxing ring', 'Heavy bags', 'Showers', 'Lockers', 'Towel service', 'Protein bar'],
    operatingHours: [
      { day: 'Monday', open: '06:00', close: '22:00' },
      { day: 'Tuesday', open: '06:00', close: '22:00' },
      { day: 'Wednesday', open: '06:00', close: '22:00' },
      { day: 'Thursday', open: '06:00', close: '22:00' },
      { day: 'Friday', open: '06:00', close: '21:00' },
      { day: 'Saturday', open: '08:00', close: '16:00' },
      { day: 'Sunday', open: '09:00', close: '14:00' },
    ],
    contactInfo: { phone: '+54 11 4815-5678', email: 'hello@fitboxarena.com.ar' },
    managerUserId: 'user-studio-2',
    status: 'approved',
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: 'studio-3',
    name: 'Core Pilates BA',
    address: 'Defensa 1100, San Telmo',
    neighborhood: 'san-telmo',
    geoCoordinates: { lat: -34.6215, lng: -58.3710 },
    description: 'Boutique Pilates studio offering reformer and mat classes in a charming San Telmo location.',
    images: ['/images/studios/core-pilates-1.jpg'],
    facilities: ['Reformer machines', 'Changing rooms', 'Filtered water', 'Mat rental'],
    operatingHours: [
      { day: 'Monday', open: '08:00', close: '20:00' },
      { day: 'Tuesday', open: '08:00', close: '20:00' },
      { day: 'Wednesday', open: '08:00', close: '20:00' },
      { day: 'Thursday', open: '08:00', close: '20:00' },
      { day: 'Friday', open: '08:00', close: '19:00' },
      { day: 'Saturday', open: '09:00', close: '14:00' },
    ],
    contactInfo: { phone: '+54 11 4300-9012', email: 'reservas@corepilatesba.com.ar' },
    managerUserId: 'user-studio-3',
    status: 'approved',
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: 'studio-4',
    name: 'Ride Cycle Club',
    address: 'Av. Cabildo 1920, Belgrano',
    neighborhood: 'belgrano',
    geoCoordinates: { lat: -34.5620, lng: -58.4540 },
    description: 'Premium indoor cycling studio with immersive lighting and top instructors. The best ride in town.',
    images: ['/images/studios/ride-cycle-1.jpg'],
    facilities: ['Spin bikes', 'Showers', 'Lockers', 'Shoe rental', 'Towels', 'Smoothie bar'],
    operatingHours: [
      { day: 'Monday', open: '06:30', close: '21:00' },
      { day: 'Tuesday', open: '06:30', close: '21:00' },
      { day: 'Wednesday', open: '06:30', close: '21:00' },
      { day: 'Thursday', open: '06:30', close: '21:00' },
      { day: 'Friday', open: '06:30', close: '20:00' },
      { day: 'Saturday', open: '08:00', close: '13:00' },
    ],
    contactInfo: { phone: '+54 11 4780-3456', email: 'info@ridecycleclub.com.ar' },
    managerUserId: 'user-studio-4',
    status: 'approved',
    rating: 4.7,
    reviewCount: 201,
  },
  {
    id: 'studio-5',
    name: 'Movimiento Libre',
    address: 'Thames 1600, Villa Crespo',
    neighborhood: 'villa-crespo',
    geoCoordinates: { lat: -34.5980, lng: -58.4380 },
    description: 'Dance and movement studio offering salsa, contemporary, tango, and freestyle classes. Express yourself!',
    images: ['/images/studios/movimiento-1.jpg'],
    facilities: ['Dance floor', 'Mirrors', 'Sound system', 'Changing rooms', 'Water fountain'],
    operatingHours: [
      { day: 'Monday', open: '10:00', close: '22:00' },
      { day: 'Tuesday', open: '10:00', close: '22:00' },
      { day: 'Wednesday', open: '10:00', close: '22:00' },
      { day: 'Thursday', open: '10:00', close: '22:00' },
      { day: 'Friday', open: '10:00', close: '21:00' },
      { day: 'Saturday', open: '10:00', close: '15:00' },
    ],
    contactInfo: { phone: '+54 11 4855-7890', email: 'hola@movimientolibre.com.ar' },
    managerUserId: 'user-studio-5',
    status: 'approved',
    rating: 4.5,
    reviewCount: 67,
  },
  {
    id: 'studio-6',
    name: 'CrossFit Río',
    address: 'Av. del Libertador 6200, Núñez',
    neighborhood: 'nuñez',
    geoCoordinates: { lat: -34.5445, lng: -58.4570 },
    description: 'Official CrossFit box with experienced coaches. WODs, Olympic lifting, and gymnastics for all levels.',
    images: ['/images/studios/crossfit-rio-1.jpg'],
    facilities: ['Full rig', 'Olympic platforms', 'Rowers', 'Assault bikes', 'Showers', 'Parking'],
    operatingHours: [
      { day: 'Monday', open: '06:00', close: '21:00' },
      { day: 'Tuesday', open: '06:00', close: '21:00' },
      { day: 'Wednesday', open: '06:00', close: '21:00' },
      { day: 'Thursday', open: '06:00', close: '21:00' },
      { day: 'Friday', open: '06:00', close: '20:00' },
      { day: 'Saturday', open: '08:00', close: '12:00' },
    ],
    contactInfo: { phone: '+54 11 4701-2345', email: 'box@crossfitrio.com.ar' },
    managerUserId: 'user-studio-6',
    status: 'approved',
    rating: 4.4,
    reviewCount: 93,
  },
  {
    id: 'studio-7',
    name: 'Equilibrio Wellness',
    address: 'Av. Rivadavia 5100, Caballito',
    neighborhood: 'caballito',
    geoCoordinates: { lat: -34.6180, lng: -58.4380 },
    description: 'Holistic wellness center offering yoga, Pilates, meditation, and stretching in a peaceful environment.',
    images: ['/images/studios/equilibrio-1.jpg'],
    facilities: ['Yoga room', 'Pilates studio', 'Meditation space', 'Herbal tea bar', 'Changing rooms'],
    operatingHours: [
      { day: 'Monday', open: '07:00', close: '21:00' },
      { day: 'Tuesday', open: '07:00', close: '21:00' },
      { day: 'Wednesday', open: '07:00', close: '21:00' },
      { day: 'Thursday', open: '07:00', close: '21:00' },
      { day: 'Friday', open: '07:00', close: '20:00' },
      { day: 'Saturday', open: '08:00', close: '14:00' },
      { day: 'Sunday', open: '09:00', close: '13:00' },
    ],
    contactInfo: { phone: '+54 11 4432-6789', email: 'namaste@equilibriowellness.com.ar' },
    managerUserId: 'user-studio-7',
    status: 'approved',
    rating: 4.7,
    reviewCount: 112,
  },
  {
    id: 'studio-8',
    name: 'Power House Gym',
    address: 'Gorriti 5800, Palermo',
    neighborhood: 'palermo',
    geoCoordinates: { lat: -34.5845, lng: -58.4355 },
    description: 'Full-service gym with HIIT, functional training, and strength classes. Personal training available.',
    images: ['/images/studios/powerhouse-1.jpg'],
    facilities: ['Free weights', 'Functional zone', 'TRX', 'Battle ropes', 'Showers', 'Lockers', 'Parking'],
    operatingHours: [
      { day: 'Monday', open: '06:00', close: '23:00' },
      { day: 'Tuesday', open: '06:00', close: '23:00' },
      { day: 'Wednesday', open: '06:00', close: '23:00' },
      { day: 'Thursday', open: '06:00', close: '23:00' },
      { day: 'Friday', open: '06:00', close: '22:00' },
      { day: 'Saturday', open: '07:00', close: '16:00' },
      { day: 'Sunday', open: '08:00', close: '14:00' },
    ],
    contactInfo: { phone: '+54 11 4775-0123', email: 'info@powerhousegym.com.ar' },
    managerUserId: 'user-studio-8',
    status: 'approved',
    rating: 4.3,
    reviewCount: 178,
  },
  {
    id: 'studio-9',
    name: 'Alma Yoga',
    address: 'Arévalo 2100, Colegiales',
    neighborhood: 'colegiales',
    geoCoordinates: { lat: -34.5740, lng: -58.4410 },
    description: 'Intimate yoga studio with small class sizes for personalized attention. Vinyasa, Hatha, and Yin.',
    images: ['/images/studios/alma-yoga-1.jpg'],
    facilities: ['Heated room', 'Mat rental', 'Props provided', 'Changing area', 'Tea corner'],
    operatingHours: [
      { day: 'Monday', open: '07:00', close: '20:00' },
      { day: 'Tuesday', open: '07:00', close: '20:00' },
      { day: 'Wednesday', open: '07:00', close: '20:00' },
      { day: 'Thursday', open: '07:00', close: '20:00' },
      { day: 'Friday', open: '07:00', close: '19:00' },
      { day: 'Saturday', open: '09:00', close: '13:00' },
    ],
    contactInfo: { phone: '+54 11 4553-4567', email: 'paz@almayoga.com.ar' },
    managerUserId: 'user-studio-9',
    status: 'approved',
    rating: 4.9,
    reviewCount: 88,
  },
  {
    id: 'studio-10',
    name: 'Estudio Nuevo',
    address: 'Av. Corrientes 3200, Almagro',
    neighborhood: 'caballito',
    geoCoordinates: { lat: -34.6050, lng: -58.4120 },
    description: 'A new fitness studio seeking approval. Offers functional training and group classes.',
    images: ['/images/studios/nuevo-1.jpg'],
    facilities: ['Functional zone', 'Changing rooms', 'Water fountain'],
    operatingHours: [
      { day: 'Monday', open: '08:00', close: '20:00' },
      { day: 'Tuesday', open: '08:00', close: '20:00' },
      { day: 'Wednesday', open: '08:00', close: '20:00' },
      { day: 'Thursday', open: '08:00', close: '20:00' },
      { day: 'Friday', open: '08:00', close: '18:00' },
    ],
    contactInfo: { phone: '+54 11 4111-2222', email: 'contacto@estudionuevo.com.ar' },
    managerUserId: 'user-studio-10',
    status: 'pending',
    rating: 0,
    reviewCount: 0,
  },
];
